[project]
name = "marimo-california"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = [
    "bpy>=4.2.0",
    "marimo>=0.9.20",
    "numpy>=2.1.3",
    "polars>=1.14.0",
    "quak>=0.2.1",
]
